import type { Metadata } from "next";
import "../assets/css/globals.css";
import "../assets/css/components.css";
import "../assets/css/animate.css";
import Header from "./layout/header";
import { ContextCommonProvider } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ContextCommonProvider>
          <Header />
          {children}
        </ContextCommonProvider>
      </body>
    </html>
  );
}
